plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


dependencies {


    dependencies {

        // 커넥션 풀 LIB
        implementation group: 'com.zaxxer', name: 'HikariCP', version: '5.1.0'
        // 개발 하는 과정에서 로그를 확인하고 싶다면 로그 찍는 라이브러리를 추가할 수 있음  -> slf4j
        // SLF4J API
        implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.17'
        // [추가] SLF4J 구현체 (Simple Logger)
        implementation group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.17'

        // Source: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
        implementation group: 'com.mysql', name: 'mysql-connector-j', version: '8.4.0'

        // Source: https://mvnrepository.com/artifact/org.projectlombok/lombok
        implementation group: 'org.projectlombok', name: 'lombok', version: '1.18.46'

        testImplementation platform('org.junit:junit-bom:6.0.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
}

test {
    useJUnitPlatform()
}